/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: analysis.proto */

#ifndef PROTOBUF_C_analysis_2eproto__INCLUDED
#define PROTOBUF_C_analysis_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Analysis__Init Analysis__Init;
typedef struct _Analysis__Data Analysis__Data;


/* --- enums --- */


/* --- messages --- */

struct  _Analysis__Init
{
  ProtobufCMessage base;
  uint32_t interval;
  uint32_t duration;
  size_t n_netint;
  char **netint;
};
#define ANALYSIS__INIT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&analysis__init__descriptor) \
    , 0, 0, 0,NULL }


struct  _Analysis__Data
{
  ProtobufCMessage base;
  int64_t time;
  char *netint;
  protobuf_c_boolean has_rstavg;
  double rstavg;
  protobuf_c_boolean has_rstmin;
  double rstmin;
  protobuf_c_boolean has_rstmax;
  double rstmax;
  protobuf_c_boolean has_rstclient;
  double rstclient;
  protobuf_c_boolean has_tp;
  double tp;
  protobuf_c_boolean has_errrate;
  double errrate;
  protobuf_c_boolean has_errratemin;
  double errratemin;
  protobuf_c_boolean has_errratemax;
  double errratemax;
  protobuf_c_boolean has_errrateclient;
  double errrateclient;
  protobuf_c_boolean has_reqrate;
  double reqrate;
  protobuf_c_boolean has_reqratemin;
  double reqratemin;
  protobuf_c_boolean has_reqratemax;
  double reqratemax;
  protobuf_c_boolean has_reqrateclient;
  double reqrateclient;
  protobuf_c_boolean has_connrate;
  double connrate;
  protobuf_c_boolean has_connratemin;
  double connratemin;
  protobuf_c_boolean has_connratemax;
  double connratemax;
  protobuf_c_boolean has_pathavg;
  double pathavg;
  protobuf_c_boolean has_pathmin;
  double pathmin;
  protobuf_c_boolean has_pathmax;
  double pathmax;
};
#define ANALYSIS__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&analysis__data__descriptor) \
    , 0, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Analysis__Init methods */
void   analysis__init__init
                     (Analysis__Init         *message);
size_t analysis__init__get_packed_size
                     (const Analysis__Init   *message);
size_t analysis__init__pack
                     (const Analysis__Init   *message,
                      uint8_t             *out);
size_t analysis__init__pack_to_buffer
                     (const Analysis__Init   *message,
                      ProtobufCBuffer     *buffer);
Analysis__Init *
       analysis__init__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   analysis__init__free_unpacked
                     (Analysis__Init *message,
                      ProtobufCAllocator *allocator);
/* Analysis__Data methods */
void   analysis__data__init
                     (Analysis__Data         *message);
size_t analysis__data__get_packed_size
                     (const Analysis__Data   *message);
size_t analysis__data__pack
                     (const Analysis__Data   *message,
                      uint8_t             *out);
size_t analysis__data__pack_to_buffer
                     (const Analysis__Data   *message,
                      ProtobufCBuffer     *buffer);
Analysis__Data *
       analysis__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   analysis__data__free_unpacked
                     (Analysis__Data *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Analysis__Init_Closure)
                 (const Analysis__Init *message,
                  void *closure_data);
typedef void (*Analysis__Data_Closure)
                 (const Analysis__Data *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor analysis__init__descriptor;
extern const ProtobufCMessageDescriptor analysis__data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_analysis_2eproto__INCLUDED */
