/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: analysis.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "analysis.pb-c.h"
void   analysis__init__init
                     (Analysis__Init         *message)
{
  static const Analysis__Init init_value = ANALYSIS__INIT__INIT;
  *message = init_value;
}
size_t analysis__init__get_packed_size
                     (const Analysis__Init *message)
{
  assert(message->base.descriptor == &analysis__init__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__init__pack
                     (const Analysis__Init *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__init__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__init__pack_to_buffer
                     (const Analysis__Init *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__init__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__Init *
       analysis__init__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__Init *)
     protobuf_c_message_unpack (&analysis__init__descriptor,
                                allocator, len, data);
}
void   analysis__init__free_unpacked
                     (Analysis__Init *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__init__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__data__init
                     (Analysis__Data         *message)
{
  static const Analysis__Data init_value = ANALYSIS__DATA__INIT;
  *message = init_value;
}
size_t analysis__data__get_packed_size
                     (const Analysis__Data *message)
{
  assert(message->base.descriptor == &analysis__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__data__pack
                     (const Analysis__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__data__pack_to_buffer
                     (const Analysis__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__Data *
       analysis__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__Data *)
     protobuf_c_message_unpack (&analysis__data__descriptor,
                                allocator, len, data);
}
void   analysis__data__free_unpacked
                     (Analysis__Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__conn__init
                     (Analysis__Conn         *message)
{
  static const Analysis__Conn init_value = ANALYSIS__CONN__INIT;
  *message = init_value;
}
size_t analysis__conn__get_packed_size
                     (const Analysis__Conn *message)
{
  assert(message->base.descriptor == &analysis__conn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__conn__pack
                     (const Analysis__Conn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__conn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__conn__pack_to_buffer
                     (const Analysis__Conn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__conn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__Conn *
       analysis__conn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__Conn *)
     protobuf_c_message_unpack (&analysis__conn__descriptor,
                                allocator, len, data);
}
void   analysis__conn__free_unpacked
                     (Analysis__Conn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__conn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__freq__init
                     (Analysis__Freq         *message)
{
  static const Analysis__Freq init_value = ANALYSIS__FREQ__INIT;
  *message = init_value;
}
size_t analysis__freq__get_packed_size
                     (const Analysis__Freq *message)
{
  assert(message->base.descriptor == &analysis__freq__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__freq__pack
                     (const Analysis__Freq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__freq__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__freq__pack_to_buffer
                     (const Analysis__Freq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__freq__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__Freq *
       analysis__freq__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__Freq *)
     protobuf_c_message_unpack (&analysis__freq__descriptor,
                                allocator, len, data);
}
void   analysis__freq__free_unpacked
                     (Analysis__Freq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__freq__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor analysis__init__field_descriptors[3] =
{
  {
    "interval",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Analysis__Init, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Analysis__Init, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "netInt",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Analysis__Init, n_netint),
    offsetof(Analysis__Init, netint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__init__field_indices_by_name[] = {
  1,   /* field[1] = duration */
  0,   /* field[0] = interval */
  2,   /* field[2] = netInt */
};
static const ProtobufCIntRange analysis__init__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor analysis__init__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.Init",
  "Init",
  "Analysis__Init",
  "analysis",
  sizeof(Analysis__Init),
  3,
  analysis__init__field_descriptors,
  analysis__init__field_indices_by_name,
  1,  analysis__init__number_ranges,
  (ProtobufCMessageInit) analysis__init__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analysis__data__field_descriptors[24] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Analysis__Data, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "netInt",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Analysis__Data, netint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rstAvg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_rstavg),
    offsetof(Analysis__Data, rstavg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rstMin",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_rstmin),
    offsetof(Analysis__Data, rstmin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rstMax",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_rstmax),
    offsetof(Analysis__Data, rstmax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rstClient",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_rstclient),
    offsetof(Analysis__Data, rstclient),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tp",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_tp),
    offsetof(Analysis__Data, tp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errRate",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_errrate),
    offsetof(Analysis__Data, errrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errRateMin",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_errratemin),
    offsetof(Analysis__Data, errratemin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errRateMax",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_errratemax),
    offsetof(Analysis__Data, errratemax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errRateClient",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_errrateclient),
    offsetof(Analysis__Data, errrateclient),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqRate",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_reqrate),
    offsetof(Analysis__Data, reqrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqRateMin",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_reqratemin),
    offsetof(Analysis__Data, reqratemin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqRateMax",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_reqratemax),
    offsetof(Analysis__Data, reqratemax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqRateClient",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_reqrateclient),
    offsetof(Analysis__Data, reqrateclient),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connRate",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_connrate),
    offsetof(Analysis__Data, connrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connRateMin",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_connratemin),
    offsetof(Analysis__Data, connratemin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connRateMax",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_connratemax),
    offsetof(Analysis__Data, connratemax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conns",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_conns),
    offsetof(Analysis__Data, conns),
    &analysis__conn__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_client),
    offsetof(Analysis__Data, client),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_path",
    21,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_req_path),
    offsetof(Analysis__Data, req_path),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_method",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_req_method),
    offsetof(Analysis__Data, req_method),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_type",
    23,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_req_type),
    offsetof(Analysis__Data, req_type),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsp_status",
    24,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_rsp_status),
    offsetof(Analysis__Data, rsp_status),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__data__field_indices_by_name[] = {
  19,   /* field[19] = client */
  15,   /* field[15] = connRate */
  17,   /* field[17] = connRateMax */
  16,   /* field[16] = connRateMin */
  18,   /* field[18] = conns */
  7,   /* field[7] = errRate */
  10,   /* field[10] = errRateClient */
  9,   /* field[9] = errRateMax */
  8,   /* field[8] = errRateMin */
  1,   /* field[1] = netInt */
  11,   /* field[11] = reqRate */
  14,   /* field[14] = reqRateClient */
  13,   /* field[13] = reqRateMax */
  12,   /* field[12] = reqRateMin */
  21,   /* field[21] = req_method */
  20,   /* field[20] = req_path */
  22,   /* field[22] = req_type */
  23,   /* field[23] = rsp_status */
  2,   /* field[2] = rstAvg */
  5,   /* field[5] = rstClient */
  4,   /* field[4] = rstMax */
  3,   /* field[3] = rstMin */
  0,   /* field[0] = time */
  6,   /* field[6] = tp */
};
static const ProtobufCIntRange analysis__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 24 }
};
const ProtobufCMessageDescriptor analysis__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.Data",
  "Data",
  "Analysis__Data",
  "analysis",
  sizeof(Analysis__Data),
  24,
  analysis__data__field_descriptors,
  analysis__data__field_indices_by_name,
  1,  analysis__data__number_ranges,
  (ProtobufCMessageInit) analysis__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analysis__conn__field_descriptors[2] =
{
  {
    "ip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Analysis__Conn, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Analysis__Conn, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__conn__field_indices_by_name[] = {
  0,   /* field[0] = ip */
  1,   /* field[1] = port */
};
static const ProtobufCIntRange analysis__conn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor analysis__conn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.Conn",
  "Conn",
  "Analysis__Conn",
  "analysis",
  sizeof(Analysis__Conn),
  2,
  analysis__conn__field_descriptors,
  analysis__conn__field_indices_by_name,
  1,  analysis__conn__number_ranges,
  (ProtobufCMessageInit) analysis__conn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analysis__freq__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Analysis__Freq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Analysis__Freq, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__freq__field_indices_by_name[] = {
  1,   /* field[1] = freq */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange analysis__freq__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor analysis__freq__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.Freq",
  "Freq",
  "Analysis__Freq",
  "analysis",
  sizeof(Analysis__Freq),
  2,
  analysis__freq__field_descriptors,
  analysis__freq__field_indices_by_name,
  1,  analysis__freq__number_ranges,
  (ProtobufCMessageInit) analysis__freq__init,
  NULL,NULL,NULL    /* reserved[123] */
};
