/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: analysis.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "analysis.pb-c.h"
void   analysis__init__init
                     (Analysis__Init         *message)
{
  static const Analysis__Init init_value = ANALYSIS__INIT__INIT;
  *message = init_value;
}
size_t analysis__init__get_packed_size
                     (const Analysis__Init *message)
{
  assert(message->base.descriptor == &analysis__init__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__init__pack
                     (const Analysis__Init *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__init__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__init__pack_to_buffer
                     (const Analysis__Init *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__init__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__Init *
       analysis__init__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__Init *)
     protobuf_c_message_unpack (&analysis__init__descriptor,
                                allocator, len, data);
}
void   analysis__init__free_unpacked
                     (Analysis__Init *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__init__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__data__init
                     (Analysis__Data         *message)
{
  static const Analysis__Data init_value = ANALYSIS__DATA__INIT;
  *message = init_value;
}
size_t analysis__data__get_packed_size
                     (const Analysis__Data *message)
{
  assert(message->base.descriptor == &analysis__data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__data__pack
                     (const Analysis__Data *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__data__pack_to_buffer
                     (const Analysis__Data *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__Data *
       analysis__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__Data *)
     protobuf_c_message_unpack (&analysis__data__descriptor,
                                allocator, len, data);
}
void   analysis__data__free_unpacked
                     (Analysis__Data *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__metric_list__init
                     (Analysis__MetricList         *message)
{
  static const Analysis__MetricList init_value = ANALYSIS__METRIC_LIST__INIT;
  *message = init_value;
}
size_t analysis__metric_list__get_packed_size
                     (const Analysis__MetricList *message)
{
  assert(message->base.descriptor == &analysis__metric_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__metric_list__pack
                     (const Analysis__MetricList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__metric_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__metric_list__pack_to_buffer
                     (const Analysis__MetricList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__metric_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__MetricList *
       analysis__metric_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__MetricList *)
     protobuf_c_message_unpack (&analysis__metric_list__descriptor,
                                allocator, len, data);
}
void   analysis__metric_list__free_unpacked
                     (Analysis__MetricList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__metric_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__metric_msg__init
                     (Analysis__MetricMsg         *message)
{
  static const Analysis__MetricMsg init_value = ANALYSIS__METRIC_MSG__INIT;
  *message = init_value;
}
size_t analysis__metric_msg__get_packed_size
                     (const Analysis__MetricMsg *message)
{
  assert(message->base.descriptor == &analysis__metric_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__metric_msg__pack
                     (const Analysis__MetricMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__metric_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__metric_msg__pack_to_buffer
                     (const Analysis__MetricMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__metric_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__MetricMsg *
       analysis__metric_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__MetricMsg *)
     protobuf_c_message_unpack (&analysis__metric_msg__descriptor,
                                allocator, len, data);
}
void   analysis__metric_msg__free_unpacked
                     (Analysis__MetricMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__metric_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__metric_avg_msg__init
                     (Analysis__MetricAvgMsg         *message)
{
  static const Analysis__MetricAvgMsg init_value = ANALYSIS__METRIC_AVG_MSG__INIT;
  *message = init_value;
}
size_t analysis__metric_avg_msg__get_packed_size
                     (const Analysis__MetricAvgMsg *message)
{
  assert(message->base.descriptor == &analysis__metric_avg_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__metric_avg_msg__pack
                     (const Analysis__MetricAvgMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__metric_avg_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__metric_avg_msg__pack_to_buffer
                     (const Analysis__MetricAvgMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__metric_avg_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__MetricAvgMsg *
       analysis__metric_avg_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__MetricAvgMsg *)
     protobuf_c_message_unpack (&analysis__metric_avg_msg__descriptor,
                                allocator, len, data);
}
void   analysis__metric_avg_msg__free_unpacked
                     (Analysis__MetricAvgMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__metric_avg_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__freq__init
                     (Analysis__Freq         *message)
{
  static const Analysis__Freq init_value = ANALYSIS__FREQ__INIT;
  *message = init_value;
}
size_t analysis__freq__get_packed_size
                     (const Analysis__Freq *message)
{
  assert(message->base.descriptor == &analysis__freq__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__freq__pack
                     (const Analysis__Freq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__freq__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__freq__pack_to_buffer
                     (const Analysis__Freq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__freq__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__Freq *
       analysis__freq__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__Freq *)
     protobuf_c_message_unpack (&analysis__freq__descriptor,
                                allocator, len, data);
}
void   analysis__freq__free_unpacked
                     (Analysis__Freq *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__freq__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__metric_cum_distr_msg__init
                     (Analysis__MetricCumDistrMsg         *message)
{
  static const Analysis__MetricCumDistrMsg init_value = ANALYSIS__METRIC_CUM_DISTR_MSG__INIT;
  *message = init_value;
}
size_t analysis__metric_cum_distr_msg__get_packed_size
                     (const Analysis__MetricCumDistrMsg *message)
{
  assert(message->base.descriptor == &analysis__metric_cum_distr_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__metric_cum_distr_msg__pack
                     (const Analysis__MetricCumDistrMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__metric_cum_distr_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__metric_cum_distr_msg__pack_to_buffer
                     (const Analysis__MetricCumDistrMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__metric_cum_distr_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__MetricCumDistrMsg *
       analysis__metric_cum_distr_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__MetricCumDistrMsg *)
     protobuf_c_message_unpack (&analysis__metric_cum_distr_msg__descriptor,
                                allocator, len, data);
}
void   analysis__metric_cum_distr_msg__free_unpacked
                     (Analysis__MetricCumDistrMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__metric_cum_distr_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   analysis__close__init
                     (Analysis__Close         *message)
{
  static const Analysis__Close init_value = ANALYSIS__CLOSE__INIT;
  *message = init_value;
}
size_t analysis__close__get_packed_size
                     (const Analysis__Close *message)
{
  assert(message->base.descriptor == &analysis__close__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t analysis__close__pack
                     (const Analysis__Close *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &analysis__close__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t analysis__close__pack_to_buffer
                     (const Analysis__Close *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &analysis__close__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Analysis__Close *
       analysis__close__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Analysis__Close *)
     protobuf_c_message_unpack (&analysis__close__descriptor,
                                allocator, len, data);
}
void   analysis__close__free_unpacked
                     (Analysis__Close *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &analysis__close__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor analysis__init__field_descriptors[8] =
{
  {
    "netInt",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Analysis__Init, n_netint),
    offsetof(Analysis__Init, netint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interval",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Analysis__Init, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Analysis__Init, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "activeMetric",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Analysis__Init, activemetric),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clientIP",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Analysis__Init, has_clientip),
    offsetof(Analysis__Init, clientip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clientPort",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Analysis__Init, has_clientport),
    offsetof(Analysis__Init, clientport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serverIP",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Analysis__Init, has_serverip),
    offsetof(Analysis__Init, serverip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serverPort",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Analysis__Init, has_serverport),
    offsetof(Analysis__Init, serverport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__init__field_indices_by_name[] = {
  3,   /* field[3] = activeMetric */
  4,   /* field[4] = clientIP */
  5,   /* field[5] = clientPort */
  2,   /* field[2] = duration */
  1,   /* field[1] = interval */
  0,   /* field[0] = netInt */
  6,   /* field[6] = serverIP */
  7,   /* field[7] = serverPort */
};
static const ProtobufCIntRange analysis__init__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor analysis__init__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.Init",
  "Init",
  "Analysis__Init",
  "analysis",
  sizeof(Analysis__Init),
  8,
  analysis__init__field_descriptors,
  analysis__init__field_indices_by_name,
  2,  analysis__init__number_ranges,
  (ProtobufCMessageInit) analysis__init__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analysis__data__field_descriptors[28] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Analysis__Data, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "netInt",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Analysis__Data, netint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rstAvg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_rstavg),
    offsetof(Analysis__Data, rstavg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rstMin",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_rstmin),
    offsetof(Analysis__Data, rstmin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rstMax",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_rstmax),
    offsetof(Analysis__Data, rstmax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rstClient",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_rstclient),
    offsetof(Analysis__Data, rstclient),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errRate",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_errrate),
    offsetof(Analysis__Data, errrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errRateMin",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_errratemin),
    offsetof(Analysis__Data, errratemin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errRateMax",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_errratemax),
    offsetof(Analysis__Data, errratemax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errRateClient",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_errrateclient),
    offsetof(Analysis__Data, errrateclient),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqRate",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_reqrate),
    offsetof(Analysis__Data, reqrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqRateMin",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_reqratemin),
    offsetof(Analysis__Data, reqratemin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqRateMax",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_reqratemax),
    offsetof(Analysis__Data, reqratemax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reqRateClient",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_reqrateclient),
    offsetof(Analysis__Data, reqrateclient),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connRate",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_connrate),
    offsetof(Analysis__Data, connrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connRateMin",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_connratemin),
    offsetof(Analysis__Data, connratemin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connRateMax",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_connratemax),
    offsetof(Analysis__Data, connratemax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client",
    18,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_client),
    offsetof(Analysis__Data, client),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_path",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_req_path),
    offsetof(Analysis__Data, req_path),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_method",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_req_method),
    offsetof(Analysis__Data, req_method),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_type",
    21,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_req_type),
    offsetof(Analysis__Data, req_type),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsp_status",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__Data, n_rsp_status),
    offsetof(Analysis__Data, rsp_status),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tpAvg",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_tpavg),
    offsetof(Analysis__Data, tpavg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tpMin",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_tpmin),
    offsetof(Analysis__Data, tpmin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tpMax",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_tpmax),
    offsetof(Analysis__Data, tpmax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tpRevAvg",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_tprevavg),
    offsetof(Analysis__Data, tprevavg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tpRevMin",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_tprevmin),
    offsetof(Analysis__Data, tprevmin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tpRevMax",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Analysis__Data, has_tprevmax),
    offsetof(Analysis__Data, tprevmax),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__data__field_indices_by_name[] = {
  17,   /* field[17] = client */
  14,   /* field[14] = connRate */
  16,   /* field[16] = connRateMax */
  15,   /* field[15] = connRateMin */
  6,   /* field[6] = errRate */
  9,   /* field[9] = errRateClient */
  8,   /* field[8] = errRateMax */
  7,   /* field[7] = errRateMin */
  1,   /* field[1] = netInt */
  10,   /* field[10] = reqRate */
  13,   /* field[13] = reqRateClient */
  12,   /* field[12] = reqRateMax */
  11,   /* field[11] = reqRateMin */
  19,   /* field[19] = req_method */
  18,   /* field[18] = req_path */
  20,   /* field[20] = req_type */
  21,   /* field[21] = rsp_status */
  2,   /* field[2] = rstAvg */
  5,   /* field[5] = rstClient */
  4,   /* field[4] = rstMax */
  3,   /* field[3] = rstMin */
  0,   /* field[0] = time */
  22,   /* field[22] = tpAvg */
  24,   /* field[24] = tpMax */
  23,   /* field[23] = tpMin */
  25,   /* field[25] = tpRevAvg */
  27,   /* field[27] = tpRevMax */
  26,   /* field[26] = tpRevMin */
};
static const ProtobufCIntRange analysis__data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 28 }
};
const ProtobufCMessageDescriptor analysis__data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.Data",
  "Data",
  "Analysis__Data",
  "analysis",
  sizeof(Analysis__Data),
  28,
  analysis__data__field_descriptors,
  analysis__data__field_indices_by_name,
  1,  analysis__data__number_ranges,
  (ProtobufCMessageInit) analysis__data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define analysis__metric_list__field_descriptors NULL
#define analysis__metric_list__field_indices_by_name NULL
#define analysis__metric_list__number_ranges NULL
const ProtobufCMessageDescriptor analysis__metric_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.MetricList",
  "MetricList",
  "Analysis__MetricList",
  "analysis",
  sizeof(Analysis__MetricList),
  0,
  analysis__metric_list__field_descriptors,
  analysis__metric_list__field_indices_by_name,
  0,  analysis__metric_list__number_ranges,
  (ProtobufCMessageInit) analysis__metric_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analysis__metric_msg__field_descriptors[6] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Analysis__MetricMsg, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Analysis__MetricMsg, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "netInt",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Analysis__MetricMsg, netint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clientId",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Analysis__MetricMsg, clientid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metricAvg",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__MetricMsg, values_case),
    offsetof(Analysis__MetricMsg, metricavg),
    &analysis__metric_avg_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metricCumDistr",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__MetricMsg, values_case),
    offsetof(Analysis__MetricMsg, metriccumdistr),
    &analysis__metric_cum_distr_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__metric_msg__field_indices_by_name[] = {
  3,   /* field[3] = clientId */
  4,   /* field[4] = metricAvg */
  5,   /* field[5] = metricCumDistr */
  0,   /* field[0] = name */
  2,   /* field[2] = netInt */
  1,   /* field[1] = time */
};
static const ProtobufCIntRange analysis__metric_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor analysis__metric_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.MetricMsg",
  "MetricMsg",
  "Analysis__MetricMsg",
  "analysis",
  sizeof(Analysis__MetricMsg),
  6,
  analysis__metric_msg__field_descriptors,
  analysis__metric_msg__field_indices_by_name,
  1,  analysis__metric_msg__number_ranges,
  (ProtobufCMessageInit) analysis__metric_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analysis__metric_avg_msg__field_descriptors[3] =
{
  {
    "avg",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Analysis__MetricAvgMsg, avg),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Analysis__MetricAvgMsg, min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Analysis__MetricAvgMsg, max),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__metric_avg_msg__field_indices_by_name[] = {
  0,   /* field[0] = avg */
  2,   /* field[2] = max */
  1,   /* field[1] = min */
};
static const ProtobufCIntRange analysis__metric_avg_msg__number_ranges[1 + 1] =
{
  { 5, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor analysis__metric_avg_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.MetricAvgMsg",
  "MetricAvgMsg",
  "Analysis__MetricAvgMsg",
  "analysis",
  sizeof(Analysis__MetricAvgMsg),
  3,
  analysis__metric_avg_msg__field_descriptors,
  analysis__metric_avg_msg__field_indices_by_name,
  1,  analysis__metric_avg_msg__number_ranges,
  (ProtobufCMessageInit) analysis__metric_avg_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analysis__freq__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Analysis__Freq, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freq",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Analysis__Freq, freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__freq__field_indices_by_name[] = {
  1,   /* field[1] = freq */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange analysis__freq__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor analysis__freq__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.Freq",
  "Freq",
  "Analysis__Freq",
  "analysis",
  sizeof(Analysis__Freq),
  2,
  analysis__freq__field_descriptors,
  analysis__freq__field_indices_by_name,
  1,  analysis__freq__number_ranges,
  (ProtobufCMessageInit) analysis__freq__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor analysis__metric_cum_distr_msg__field_descriptors[1] =
{
  {
    "freqs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Analysis__MetricCumDistrMsg, n_freqs),
    offsetof(Analysis__MetricCumDistrMsg, freqs),
    &analysis__freq__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned analysis__metric_cum_distr_msg__field_indices_by_name[] = {
  0,   /* field[0] = freqs */
};
static const ProtobufCIntRange analysis__metric_cum_distr_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor analysis__metric_cum_distr_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.MetricCumDistrMsg",
  "MetricCumDistrMsg",
  "Analysis__MetricCumDistrMsg",
  "analysis",
  sizeof(Analysis__MetricCumDistrMsg),
  1,
  analysis__metric_cum_distr_msg__field_descriptors,
  analysis__metric_cum_distr_msg__field_indices_by_name,
  1,  analysis__metric_cum_distr_msg__number_ranges,
  (ProtobufCMessageInit) analysis__metric_cum_distr_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define analysis__close__field_descriptors NULL
#define analysis__close__field_indices_by_name NULL
#define analysis__close__number_ranges NULL
const ProtobufCMessageDescriptor analysis__close__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "analysis.Close",
  "Close",
  "Analysis__Close",
  "analysis",
  sizeof(Analysis__Close),
  0,
  analysis__close__field_descriptors,
  analysis__close__field_indices_by_name,
  0,  analysis__close__number_ranges,
  (ProtobufCMessageInit) analysis__close__init,
  NULL,NULL,NULL    /* reserved[123] */
};
