language: c

before_script:
  - sudo apt-get install libpcap-dev
  - git clone https://github.com/json-c/json-c.git
  - cd json-c
  - sh autogen.sh
  - ./configure && make
  - sudo make install && cd -

script: scons
